# Generated by Django 5.2.5 on 2025-08-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ppublication_year',
            new_name='publication_year',
        ),
    ]
